
title: knihkupka
subtitle: knihkupectví v Novém Strašecí
logo: /assets/images/logo.svg

email: knihkupka@knihkupa.cz
description: Knihkupka, knihkupectví v Novém Strašecí.  
minimal_mistakes_skin: default
search: false
locale: cs-CZ


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Prague # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _includes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
   name   : "Knihkupka, knihkupectví v Novém Strašecí"
#   avatar : "/assets/images/bio-photo.jpg"
#   bio    : "My awesome biography constrained to a sentence or two goes here."
  # links:
  #   - label: "Website"
  #     icon: "fas fa-fw fa-link"
  #     url: "https://"
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://twitter.com/"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/"
  #   - label: "Instagram"
  #     icon: "fab fa-fw fa-instagram"
  #     url: "https://instagram.com/"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/knihkupka"
    - label: "Napište nám"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:knihkupka@knihkupka.cz"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      # author_profile: true
      # read_time: true
      # comments: true
      # share: true
      # related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
     # author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
